jaffle_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('JAFFLE_POSTGRES_HOST') }}"
      user: "{{ env_var('JAFFLE_POSTGRES_USER') }}"
      password: "{{ env_var('JAFFLE_POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('JAFFLE_POSTGRES_DB') }}"
      schema: "jaffle_shop"
